baseurl = "http://key-amb.github.io/poloxy-doc"
languageCode = "en-us"
title = "poloxy"
theme = "bootie-docs"
copyright = "Copyright (c) 2016, YASUTAKE Kiyoshi; All rights reserved."

[params]
  description = "Buffering proxy system for alerting"
  #withSitePosts = true
  searchDomain = "key-amb.github.io/poloxy-doc"
  noCategoryLink = true
  repositoryUrl = "https://github.com/key-amb/poloxy/"
  highlightStyle = "atelier-forest-dark"

[[params.mainMenu]]
  name = "Intro"
  link = "introduction"

[[params.mainMenu]]
  name = "Bootstrap"
  link = "getting-started"

[[params.mainMenu]]
  name = "Usage"
  link = "usage"
