baseurl = "https://progrhy.me/poloxy-doc"
languageCode = "en-us"
title = "poloxy"
theme = "bootie-docs"
copyright = "Copyright (c) 2016-2017, IKEDA Kiyoshi; All rights reserved."

[params]
  description = "Buffering proxy system for alerting"
  #withSitePosts = true
  searchDomain = "progrhyme.github.io/poloxy-doc"
  noCategoryLink = true
  repositoryUrl = "https://github.com/progrhyme/poloxy/"
  highlightStyle = "atelier-forest-dark"

[[menu.main]]
  name   = "Intro"
  url    = "/introduction/"
  weight = 20

[[menu.main]]
  name   = "Bootstrap"
  url    = "/getting-started/"
  weight = 30

[[menu.main]]
  name   = "Usage"
  url    = "/usage/"
  weight = 40
